<?php
/**
 * @file
 * DEIMS data explorer allows users to view and download remote data sources.
 */

require_once dirname(__FILE__) . '/inc/variable_availability.inc';

/**
 * Define the maximum number of rows to display in the data preview.
 */
define("DEIMS_PREVIEW_COUNT", variable_get('deims_preview_count', 20));

/**
 * Define the maximum number of rows to be downloaded.
 */
define("DEIMS_DOWNLOAD_COUNT", variable_get('deims_download_count', 99999));

/**
 * Define the maximum number of rows be downloaded.
 */
define("DEIMS_BATCH_LIMIT", variable_get('deims_batch_limit', 500));

/**
 * Define the smallest size file that will be compressed (in MB).
 */
define("DEIMS_COMPRESSION_THRESHOLD", variable_get('deims_compression_threshold', 2));

/**
 * Implements hook_help().
 */
function deims_data_explorer_help($path, $arg) {
  switch ($path) {
    case 'admin/help#deims_data_explorer':
      return t("TODO: Create admin help text.");
  }
}

/**
 * Implements hook_menu().
 */
function deims_data_explorer_menu() {
  $items = array();
  $items['node/%node/data'] = array(
    'page callback' => 'deims_data_explorer_page',
    'page arguments' => array(1),
    'access callback'  => 'node_access',
    'access arguments' => array('view', 1),
    'type' => MENU_CALLBACK,
  );
  $items['explorer/%file/%node'] = array(
    'page callback' => 'deims_data_explorer_download',
    'page arguments' => array(1, 2),
    'access callback' => 'node_access',
    'access arguments' => array('view', 2),
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Implements hook_permission().
 */
function deims_data_explorer_permission() {
  // @todo Is this permission actually used anywhere?
  return array(
    'administer deims data explorer' => array(
      'title' => t('Administer DEIMS data explorer'),
      'description' => t('Perform administration tasks for DEIMS data explorer.'),
    ),
  );
}

/**
 * @todo Document deims_data_explorer_page .
 *
 * @param $node
 *
 * @return int
 */
function deims_data_explorer_page($node) {
  // @todo Determine any other checks we need to do.
  if ($node->type != 'data_source') {
    return MENU_NOT_FOUND;
  }

  $connection = field_get_items('node', $node, 'field_deims_data_explorer');
  $variables  = field_get_items('node', $node, 'field_variables');

  if (!empty($connection) && !empty($variables)) {
    $form = drupal_get_form('deims_data_explorer_form', $variables, $connection[0]);
    return $form;
  }
  else {
    return MENU_NOT_FOUND;
  }
}


/**
 * @todo Document deims_data_explorer_form .
 *
 * @param $form
 * @param $form_state
 * @param $columns
 * @param $variables
 *
 * @return mixed
 */
function deims_data_explorer_form($form, &$form_state, $variables, $connection) {

  // Get the allowed columns from the data source variable definitions.
  $allowed_column_variables = _deims_de_get_allowed_columns($variables);
  // Get allowed filters from the data source variable definitions.
  $allowed_filters_variables = _deims_de_get_allowed_filters($variables);

  // Flatten the array of columns & filters to just the name value.
  $allowed_columns = _deims_de_flatten_allowed($allowed_column_variables);
  $allowed_filters = _deims_de_flatten_allowed($allowed_filters_variables);

  // Check if the form has been submitted.
  if (isset($form_state['values']['op'])) {
    // Get columns submitted in the form.
    $submitted_columns = _deims_de_get_submitted_columns($form_state['values']['columns_table']);

    // Take only the columns submitted AND are allowed.
    $columns = array_intersect($allowed_columns, $submitted_columns);

    // Get filters submitted in the form.
    $submitted_filters = _deims_de_get_submitted_filters($form_state['values']['filters_table']);

    // Take only the filters submitted AND are allowed.
    $filters = array_intersect($allowed_filters, $submitted_filters);

    switch ($form_state['values']['op']) {
      case 'Web Preview':
        $data = deims_data_explorer_get_rows($connection, $columns, $filters, DEIMS_PREVIEW_COUNT);
        $total_rows = deims_data_explorer_get_row_count($connection, $columns);

        $form['results'] = array(
          '#markup' => deims_data_explorer_generate_preview($columns, $data, $total_rows),
        );

        return $form;
        break;

      case 'Download':
        $file = file_save_data('', file_create_filename($connection['table'], 'public://'));

        $options = array(
          'connection' => $connection,
          'columns' => $columns,
          'filters' => $filters,
          'total_rows' => deims_data_explorer_get_row_count($connection, $columns),
          'limit' => DEIMS_BATCH_LIMIT,
          'file' => $file,
        );

        // Set up the batch process.
        $batch = array(
          'title' => 'Processing Data Set',
          'operations' => array(
            array('_fetch_row_batch', array($options)),
            array('_process_file_for_download', array($file, $connection['table'])),
          ),
          'finished' => '_show_download_link',
          'file' => drupal_get_path('module', 'deims_data_explorer') . '/deims_data_explorer.batch.inc'
        );

        batch_set($batch);

        // @todo: Need to fix this so it's not hard-coded.
        // Create page callback where download text stands out a little more
        // and also make sure to link back to the data set.
        batch_process('node/24/data');

        break;
    }
  }

  // START: Create the table to select columns.
  $form['columns_set'] = array(
    '#type' => 'fieldset',
    '#title' => t('Please select what columns you would like to include.'),
  );

  $header  = array(
    'label' => t('Label'),
    'name' => t('Variable Name'),
    'type' => t('Variable Type'),
    'definition' => t('Definition'),
  );
  $options = array();
  foreach ($allowed_column_variables as $variable) {
    $options[$variable['name']] = array(
      'label' => $variable['label'],
      'name' => $variable['name'],
      'type' => $variable['type'],
      'definition' => $variable['definition'],
    );
  }
  $form['columns_set']['columns_table'] = array(
    '#type' => 'tableselect',
    '#header' => $header,
    '#options' => $options,
    '#empty' => t('No columns found'),
  );
  // END: Create the table to select columns.


  // START: Create the table to select filters.
  $form['filter_set'] = array(
    '#type' => 'fieldset',
    '#title' => t('Please choose any filters you would like to add.'),
  );

  $header = array(
    'label' => t('Label'),
    'choice' => t('Choice'),
  );
  $options = array();
  foreach ($allowed_filters_variables as $variable) {
    $options[$variable['name']] = array(
      'label' => $variable['label'],
      'choice' => 'Choice',
    );
  }
  $form['filter_set']['filters_table'] = array(
    '#type' => 'tableselect',
    '#header' => $header,
    '#options' => $options,
    '#empty' => t('No filters found'),
  );
  // END: Create the table to select filters.

  //deims_de_prep_variables($variables, $form);

  $form['preview'] = array(
    '#type' => 'submit',
    '#value' => 'Web Preview',
  );

  $form['download'] = array(
    '#type' => 'submit',
    '#value' => 'Download',
  );

  // Add logic for download button disable and warning.
  if (deims_data_explorer_get_row_count($connection, $allowed_columns) >= DEIMS_DOWNLOAD_COUNT) {
    drupal_set_message('This is a very large data set. Please ' . l('contact us', 'contact') .
      ' to obtain a copy.', 'warning', FALSE);
    unset($form['download']);
  }
  return $form;
}

function deims_data_explorer_form_submit($form, &$form_state) {
  // Exclude unnecessary elements.
  //unset($form_state['values']['submit'], $form_state['values']['form_id'], $form_state['values']['op'], $form_state['values']['form_token'], $form_state['values']['form_build_id']);

  foreach ($form_state['values'] as $key => $value) {
    // drupal_set_message(t('%name has value %value', array('%name' => $key, '%value' => print_r($value, TRUE))));
  }
  $form_state['rebuild'] = TRUE;
}

/**
 * @todo Document
 *
 * @param array $item
 *
 * @return string
 */
function deims_data_explorer_generate_preview($columns_array, $rows_array, $total_rows = 0) {
  $count = null;
  if ($total_rows >= DEIMS_PREVIEW_COUNT) {
    $count = '<div class="deims-row-count">Showing <strong>' . DEIMS_PREVIEW_COUNT . '</strong>
    of <strong>'. $total_rows . '</strong> records';
  }

  $markup = $count . theme('table', array(
    'header' => $columns_array,
    'rows'   => $rows_array,
  )) . $count;

  return $markup;
}

/**
 * @todo Document _deims_de_get_allowed_columns .
 *
 * @param $variables
 *
 * @return array
 */
function _deims_de_get_allowed_columns($variables) {
  return $variables;
}

/**
 * @todo Document _deims_de_get_allowed_filters .
 *
 * @param $variables
 *
 * @return array
 */
function _deims_de_get_allowed_filters($variables) {
  return $variables;
}

function _deims_de_get_submitted_columns($columns) {
  $return = array();
  foreach ($columns as $key => $value) {
     if ($key == $value) {
       $return[] = $value;
     }
  }
  return $return;
}

function _deims_de_get_submitted_filters($columns) {
  $return = array();
  foreach ($columns as $key => $value) {
    if ($key == $value) {
      $return[] = $value;
    }
  }
  return $return;
}

function _deims_de_flatten_allowed($variables) {
  // @todo Change these to return the full variables and use the array map only where needed.
  // @todo Change to only include checked columns.
  return array_map(function ($value) { return $value['name']; }, $variables);
}

/**
 * [deims_data_explorer_get_row_count description]
 * @param  [type] $connection [description]
 * @return [type]             [description]
 */
function deims_data_explorer_get_row_count($connection) {
  $query = db_select($connection['table'], 't')
    ->fields('t')
    ->execute();
  return $query->rowCount();
}

/**
 * @todo Document deims_data_explorer_get_rows .
 *
 * @param $connection
 * @param array $columns
 * @param array $conditions
 * @param int $limit
 *
 * @return array
 */
function deims_data_explorer_get_rows($connection, $columns = array(), $conditions = array(), $limit = 20, $from = 0) {

  $db_connection = Database::getConnection('default', $connection['connection']);

  $result = $db_connection->select($connection['table'], 't')
    ->fields('t', $columns)
    ->range($from,$limit)
    ->execute();

  return $result->fetchAll(PDO::FETCH_ASSOC);
}

function _deims_de_prep_variable($variable, &$form) {
  if ($variable['type'] == '') {
    $variable['type'] = 'nominal';
  }
  $function = '_deims_de_prep_' . $variable['type'];
  if (function_exists($function)) {
    // Add to form.
    $function($variable, $form);
  }
}

function _deims_de_prep_variables($variables, &$form) {
  foreach ($variables as $variable) {
    if ($variable['type'] == '') {
      $variable['type'] = 'nominal';
    }
    $function = '_deims_de_prep_' . $variable['type'];
    if (function_exists($function)) {
      // Add to form.
      $function($variable, $form);
    }
    else {

    }
  }
}

/**
 * @todo Document _deims_prep_list .
 *
 * @param $variable
 */
function _deims_de_prep_codes($variable, &$form) {
  $codes = $variable['data']['codes'];
  $code_list = array();
  foreach ($codes as $key => $value) {
    $code_list[] = $key;
  }
  $name = $variable['name'];
  $form['filter_set'][$name] = array(
    '#type' => 'fieldset',
    '#title' => $name,
  );
  $form['filter_set'][$name][$name] = array(
    '#type' => 'checkboxes',
    '#options' => $code_list,
    '#title' => t('Limit by search codes:'),
  );
}

/**
 * @todo Document _deims_de_prep_nominal .
 *
 * @param $variable
 */
function _deims_de_prep_nominal($variable, &$form) {
  $name = $variable['name'];
  $form['filter_set'][$name] = array(
    '#type' => 'fieldset',
    '#title' => $name,
  );
  $form['filter_set'][$name][$name] = array(
    '#type' => 'textfield',
    '#title' => t('Limit by search term:'),
  );
}

/**
 * @todo Document _deims_de_prep_physical .
 *
 * @param $variable
 */
function _deims_de_prep_physical($variable, &$form) {

  $name = $variable['name'];
  $minimum = $variable['data']['minimum'];
  $maximum = $variable['data']['maximum'];
  $unit = $variable['data']['unit'];
  $precision = $variable['data']['precision'];
  $options = array();
  foreach (range($minimum, $maximum, $precision) as $number) {
    $options[] = $number;
  }
  $form['filter_set'][$name] = array(
    '#type'  => 'fieldset',
    '#title' => $name,
  );
// @todo Fix
  $form['filter_set'][$name][$name]['min'] = array(
    '#type'          => 'select',
    '#title'         => t("Choose a minimum $unit:"),
    '#options'       => $options,
    '#default_value' => $minimum,
  );
  $form['filter_set'][$name][$name]['max'] = array(
    '#type'          => 'select',
    '#title'         => t("Choose a maximum $unit:"),
    '#options'       => $options,
    '#default_value' => 10,
  );
}

/**
 * [deims_data_explorer_download description]
 */
function deims_data_explorer_download($file, $node) {
  $uri = file_entity_download_uri($file);
  $output =  array(
    'header' => array(
      '#type' => 'markup',
      '#markup' => '<h2>File ready for download</h2>',
    ),
    'info' => array(
      '#type' => 'markup',
      '#markup' => '<p>Your file is ready to be downloaded. It will be available
      for the next few hours. Please download it now.</p><p>'
      . l('Click here', $uri['path'], $uri['options']) . ' to download the
      file.</p>',
    ),
    'back' => array(
      '#type' => 'markup',
      '#markup' => '<p>' . l('Return to data set', "node/{$node->nid}") . '</p>',
    ),
  );
  return $output;
}

/**
 * @todo Document _deims_de_prep_date .
 *
 * @param $variable
 * @param $
 */
function _deims_de_prep_date($variable, &$form) {

  dpr($variable);
}

/**
 * @todo Document _deims_de_array2csv .
 *
 * @param array $array
 *
 * @return null|string
 */
function _deims_de_array2csv(array &$array) {
  if (count($array) == 0) {
    return NULL;
  }
  ob_start();
  $df = fopen("php://output", 'w');
  fputcsv($df, array_keys(reset($array)));
  foreach ($array as $row) {
    fputcsv($df, $row);
  }
  fclose($df);

  return ob_get_clean();
}
